package main

import (
	"image"
	_ "image/png"
	"os"
	"path/filepath"
	"testing"
	"time"

	maa "github.com/MaaXYZ/maa-framework-go/v4"
)

// This file exercises the real mechanism end to end, without the game:
//
//	a synthetic 1280x720 screenshot (testdata/rock_bar.png, generated by
//	testdata/gen_fixture.py) is served by a custom controller, the project's
//	resource bundle is loaded (including the OCR models), and the pipeline node
//	PickLeastRock is run for real. What is under test:
//
//	  1. OCR on the five ROIs -> counts -> argmin -> OverrideNext actually routes
//	     the task into the expected cave node;
//	  2. when nothing can be read, the task FAILS (red cross) instead of falling
//	     back to some default cave — the requirement behind「读不到必须报错」.
//
// The five cave nodes are overridden to DirectHit+DoNothing so that only the
// routing is asserted, not the game's own OCR of the cave entrances.

const rockBarFixture = "agent/rock-picker/testdata/rock_bar.png"
const rockBarBlankFixture = "agent/rock-picker/testdata/rock_bar_blank.png"

// fixtureController serves one immutable screenshot, like a paused game window.
type fixtureController struct {
	img image.Image
}

func (c *fixtureController) Connect() bool                                { return true }
func (c *fixtureController) Connected() bool                              { return true }
func (c *fixtureController) RequestUUID() (string, bool)                  { return "fixture", true }
func (c *fixtureController) GetFeature() maa.ControllerFeature            { return maa.ControllerFeatureNone }
func (c *fixtureController) StartApp(string) bool                         { return true }
func (c *fixtureController) StopApp(string) bool                          { return true }
func (c *fixtureController) Screencap() (image.Image, bool)               { return c.img, true }
func (c *fixtureController) Click(int32, int32) bool                      { return true }
func (c *fixtureController) Swipe(int32, int32, int32, int32, int32) bool { return true }
func (c *fixtureController) TouchDown(int32, int32, int32, int32) bool    { return true }
func (c *fixtureController) TouchMove(int32, int32, int32, int32) bool    { return true }
func (c *fixtureController) TouchUp(int32) bool                           { return true }
func (c *fixtureController) ClickKey(int32) bool                          { return true }
func (c *fixtureController) InputText(string) bool                        { return true }
func (c *fixtureController) KeyDown(int32) bool                           { return true }
func (c *fixtureController) KeyUp(int32) bool                             { return true }
func (c *fixtureController) Scroll(int32, int32) bool                     { return true }
func (c *fixtureController) RelativeMove(int32, int32) bool               { return true }
func (c *fixtureController) Shell(string, int64) (string, bool)           { return "", true }
func (c *fixtureController) Inactive() bool                               { return true }
func (c *fixtureController) GetInfo() (string, bool)                      { return "", true }

// repoRoot walks up from the package directory to the repository root, which is
// identified by interface.json. Everything the test needs (maafw/, resource/)
// lives there, so the test silently skips outside a full checkout.
func repoRoot(t *testing.T) string {
	t.Helper()

	dir, err := filepath.Abs(".")
	if err != nil {
		t.Skipf("cannot resolve working directory: %v", err)
	}
	for i := 0; i < 6; i++ {
		if _, err := os.Stat(filepath.Join(dir, "interface.json")); err == nil {
			return dir
		}
		dir = filepath.Dir(dir)
	}
	t.Skip("repository root (interface.json) not found; skipping the integration test")
	return ""
}

func loadFixture(t *testing.T, path string) image.Image {
	t.Helper()

	f, err := os.Open(path)
	if err != nil {
		t.Skipf("fixture %s not found; run agent/rock-picker/testdata/gen_fixture.py first: %v", path, err)
	}
	defer f.Close()

	img, _, err := image.Decode(f)
	if err != nil {
		t.Fatalf("decode %s: %v", path, err)
	}
	return img
}

// mustTasker wires resource + controller exactly like MXU does, registers the
// recognition on the resource (the agent server does the same in production),
// and returns a ready tasker.
func mustTasker(t *testing.T, repo string, ctrlImg image.Image) *maa.Tasker {
	t.Helper()

	if err := maa.Init(maa.WithLibDir(filepath.Join(repo, "maafw"))); err != nil {
		t.Skipf("cannot load MaaFramework from maafw/: %v", err)
	}

	res, err := maa.NewResource()
	if err != nil {
		t.Fatalf("NewResource: %v", err)
	}
	if !res.PostBundle(filepath.Join(repo, "resource")).Wait().Success() {
		t.Fatalf("PostBundle(resource) failed — check resource/ and resource/model/ocr")
	}
	if err := res.RegisterCustomRecognition(leastRockRecognitionName, &LeastRockPicker{}); err != nil {
		t.Fatalf("RegisterCustomRecognition: %v", err)
	}

	ctrl, err := maa.NewCustomController(&fixtureController{img: ctrlImg})
	if err != nil {
		t.Fatalf("NewCustomController: %v", err)
	}
	ctrl.PostConnect().Wait()

	tasker, err := maa.NewTasker()
	if err != nil {
		t.Fatalf("NewTasker: %v", err)
	}
	if err := tasker.BindResource(res); err != nil {
		t.Fatalf("BindResource: %v", err)
	}
	if err := tasker.BindController(ctrl); err != nil {
		t.Fatalf("BindController: %v", err)
	}
	if !tasker.Initialized() {
		t.Fatalf("tasker not initialized")
	}
	return tasker
}

// caveOverride turns the five cave nodes into trivially-hittable stubs so the
// assertion is purely about which one PickLeastRock routes into. It also gives
// PickLeastRock a one-second budget: its own internal retries are what matter,
// the framework must not spin for the default twenty seconds in a test.
func caveOverride() map[string]any {
	stub := func() map[string]any {
		return map[string]any{
			"recognition": map[string]any{"type": "DirectHit"},
			"action":      map[string]any{"type": "DoNothing"},
			"next":        []string{},
		}
	}
	override := map[string]any{
		"FireRock": stub(), "WaterRock": stub(), "WindRock": stub(),
		"LightRock": stub(), "DarkRock": stub(),
		"PickLeastRock": map[string]any{"timeout": 1000},
	}
	return override
}

// nodeNames flattens the executed nodes of a finished task.
func nodeNames(t *testing.T, tasker *maa.Tasker, detail *maa.TaskDetail) []string {
	t.Helper()

	names := make([]string, 0, len(detail.Nodes))
	for _, ref := range detail.Nodes {
		node, err := ref.GetDetail()
		if err != nil {
			t.Fatalf("node detail: %v", err)
		}
		names = append(names, node.Name)
	}
	return names
}

func TestRockPickerRoutesToLeast(t *testing.T) {
	repo := repoRoot(t)
	img := loadFixture(t, filepath.Join(repo, rockBarFixture))
	tasker := mustTasker(t, repo, img)

	detail, err := tasker.PostTask("PickLeastRock", caveOverride()).Wait().GetDetail()
	if err != nil {
		t.Fatalf("PostTask: %v", err)
	}

	names := nodeNames(t, tasker, detail)
	t.Logf("executed nodes: %v", names)

	if detail.Status != maa.StatusSuccess {
		t.Fatalf("task status = %v, want success", detail.Status)
	}
	// 9177 (水) is the smallest of 13010/9177/12008/10722/16724.
	const want = "WaterRock"
	found := false
	for _, n := range names {
		if n == want {
			found = true
		}
	}
	if !found {
		t.Fatalf("expected the task to route into %s, executed nodes = %v", want, names)
	}
	for _, n := range names {
		if n == "FireRock" {
			t.Fatalf("routed into FireRock instead of %s (nodes = %v)", want, names)
		}
	}
}

// TestRockPickerFailsWhenUnreadable is the regression test for the requirement
// 「读不到要报错」: nothing readable in the frame must end the task as a
// FAILURE, never as a green check that silently skipped the hunt.
func TestRockPickerFailsWhenUnreadable(t *testing.T) {
	repo := repoRoot(t)
	img := loadFixture(t, filepath.Join(repo, rockBarBlankFixture))
	tasker := mustTasker(t, repo, img)

	start := time.Now()
	detail, err := tasker.PostTask("PickLeastRock", caveOverride()).Wait().GetDetail()
	if err != nil {
		t.Fatalf("PostTask: %v", err)
	}
	t.Logf("unreadable fixture: status = %v after %s", detail.Status, time.Since(start).Round(time.Millisecond))

	if detail.Status != maa.StatusFailure {
		t.Fatalf("task status = %v, want failure (an unreadable resource bar must fail the task, not fall back)", detail.Status)
	}
}
